"""-----------------------------------------------------------------
Config parameters are written to a python module config.py which is
imported by the main processing worker script wit_metrics_worker.py
#
This file is generated by the wit-metrics.ipynb notebook and should not be modified directly.
Instead, modify the parameters in the notebook and then run the notebook to generate the config.py file.
-----------------------------------------------------------------
"""

from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict
import os
import multiprocessing as mp


@dataclass(frozen=True)
class WITMetricsConfig:
    BASE_DIR: Path = Path(__file__).parent
    INPUT_DIR: Path = BASE_DIR / "input"
    OUTPUT_DIR: Path = BASE_DIR / "output"
    LOG_DIR: Path = BASE_DIR / "log"

    # shapefile: the shape file mentioned above to find the  and get their area
    # set to '' to disable area lookup
    SHAPEFILE_PATH: Path = INPUT_DIR / "shp/ANAEv3_test.shp"

    # shapefile field name that identifies each polygon -  the ANAEv3 UID geohash was used here.
    # The ANAE UID is also used in the naming convention for the CSV files
    SHAPEFILE_KEY: str = "UID"

    # Path to folder that contains the WIT csv files to process.  When debugging providing a single file might be prudent.
    WIT_CSV_PATH: Path = INPUT_DIR / "csv"

    # Only use WIT data where the pc_missing is less than the threshold (default is 0.1) i.e. >90% of the polygon was visible to satellites
    PC_MISSING_THRESHOLD: float = 0.1

    # csv feature_id - the WIT csv output files include a column 'feature_id' that in this case is the ANAE UID
    WIT_FEATURE_ID: str = "feature_id"

    # whether to interpolate the WIT observation dates (typically 10-50+ per year) to daily data (365 per year)
    # This is computationally expensive but improves estimates of inundation duration and time since last inundation.
    # Monthly WIT stats require interpolated daily data to infill missing records and will not be generated if interpolate_to_daily = False
    INTERPOLATE_TO_DAILY: bool = True

    # set to True to save the interpolated daily WIT csv in a subfolder under the csv_files (unnecessary and take up a lot of space but good for debugging)
    SAVE_INTERPOLATED_CSV: bool = False

    # monthly metrics files are too big for most computers when all metrics are used (e.g. just 4 metrics x 270,000 polygons x 450 months is a 5GB csv file)
    # specify a subset that will be joined together into the monthly result - must include ["feature_id","date", at-least-one-metric]\
    MONTHLY_SUBSET: list | None = None  # do not prune
    # monthly_subset=[
    #         "feature_id",
    #         "date",
    #         "water_median",
    #         "wet_median",
    #         "pv_median",
    #         "npv_median",
    #         "bs_median",
    #         "count",
    #     ]

    # set to true to save intermediate data frames containing the event times and stats
    # these are saved in the working directory
    DEBUG_EVENT_TIMES: bool = True

    # batchsize is the number of WIT csv files to include in each 'batch' that is processed by each single CPU core.
    # The code was designed to process several 100,000 polygons in small batches that fit into the computer memory
    # then glue all the batch results together at the end.
    # On a workstation with 16 cpu cores and 64MB RAM a batchsize of 100-200 worked well. With smaller number of CSV a batch size < total number of CSV allows the
    # calculations to be spread across multiple processors.
    # during processing the code will generate outputs for each batch then glue them together at the end.

    BATCH_SIZE: int = 100

    # tag prepended to final result files (zipped csv)
    TAG: str = "RESULT"

    # Whether to zip the final result csv to save space (python/pandas can read the csv from the zips)
    ZIP_RESULT: bool = False

    # define threshold and bounds to define inundation events
    THRESHOLD_PERCENTILE: float = (
        0.3  # 0.3 = 30th percentile of 'water+wet' area (lower than 0.5 keeps the median in the inundated state
    )
    MIN_THRESHOLD: float = (
        0.05  # Floor for dry sites. (0.05=5% area) stops noise and minimal water detection inclusion as inundation event
    )
    MAX_THRESHOLD: float = (
        0.50  # Cap for very wet sites. permanent lake is still considered inundated until falls below 50% water by area
    )


# ###########################################################

wit_metrics_cfg = WITMetricsConfig()
