#-----------------------------------------------------------------
# Config parameters are written to a python module config.py which is
# imported by the main processing worker script wit_metrics_worker.py
#
# This file is generated by the wit-metrics.ipynb notebook and should not be modified directly.
# Instead, modify the parameters in the notebook and then run the notebook to generate the config.py file.
#-----------------------------------------------------------------

# set the working directory - needs to have enough free space for the generated outputs (50 GB for full ANAE set)
working_directory = "d:/wit-metrics/output"

# shapefile: the shape file mentioned above to find the  and get their area
# set to '' to disable area lookup
shapefile = "d:/wit-metrics/input/shp/ANAEv3_test.shp"

# shapefile field name that identifies each polygon -  the ANAEv3 UID geohash was used here.
# The ANAE UID is also used in the naming convention for the CSV files
shape_uid = "UID"

# Path to folder that contains the WIT csv files to process.  When debugging providing a single file might be prudent.
csv_files = "d:/wit-metrics/input/csv"

#Only use WIT data where the pc_missing is less than the threshold (default is 0.1) i.e. >90% of the polygon was visible to satellites
pc_missing_threshold = 0.1

# csv feature_id - the WIT csv output files include a column 'feature_id' that in this case is the ANAE UID
pkey = "feature_id"

# whether to interpolate the WIT observation dates (typically 10-50+ per year) to daily data (365 per year)
# This is computationally expensive but improves estimates of inundation duration and time since last inundation.
# Monthly WIT stats require interpolated daily data to infill missing records and will not be generated if interpolate_to_daily = False
interpolate_to_daily = True

# set to True to save the interpolated daily WIT csv in a subfolder under the csv_files (unnecessary and take up a lot of space but good for debugging)
save_interpolated_csv = False

#monthly metrics files are too big for most computers when all metrics are used (e.g. just 4 metrics x 270,000 polygons x 450 months is a 5GB csv file)
# specify a subset that will be joined together into the monthly result - must include ["feature_id","date", at-least-one-metric]
monthly_subset=[
        "feature_id",
        "date",
        "water_median",
        "wet_median",
        "pv_median",
        "npv_median",
        "bs_median",
        "count",
    ]

# set to true to save intermediate data frames containing the event times and stats
# these are saved in the working directory
debug_event_times = False

# batchsize is the number of WIT csv files to include in each 'batch' that is processed by each single CPU core.
# The code was designed to process several 100,000 polygons in small batches that fit into the computer memory
# then glue all the batch results together at the end.
# On a workstation with 16 cpu cores and 64MB RAM a batchsize of 100-200 worked well. With smaller number of CSV a batch size < total number of CSV allows the
# calculations to be spread across multiple processors.
# during processing the code will generate outputs for each batch then glue them together at the end.

batch_size = 100

# ###########################################################
# # specific config used for Flow-MER Project annual analysis
# # this should be commented out or deleted for anyone else
# csv_files = r"M:\ANAE_WIT_07082025"
# working_directory = r"M:\ANAE_WIT_07082025_RESULTS"
# shapefile = r"M:\ANAEv3_WIT_clean16052025\ANAEv3_WIT.shp"
# monthly_subset=[
#         "feature_id",
#         "date",
#         "water+wet_median",
#         "npv+pv+wet_median",
#         "pv_median",
#         "count",
#     ]
# ###########################################################
